// ============================================================
// БАЗА ПЕРСОНАЖЕЙ
// ------------------------------------------------------------
// Чтобы добавить нового персонажа — скопируйте один из объектов
// ниже, вставьте перед закрывающей "];" и заполните поля. Либо
// используйте редактор tools/editor.html — там те же поля в виде
// формы с выпадающими списками, ничего писать руками не нужно.
//
// ФОТО ПОДБИРАЕТСЯ АВТОМАТИЧЕСКИ ПО ID. Заполните поле "id" —
// это игровой ID персонажа (айди игрока) — и положите файл с фото
// в папку images/ под именем <id>.jpg (подойдёт и .jpeg/.png/.webp,
// сайт сам перебирает расширения). Пример: id: "205834" -> файл
// images/205834.jpg. Редактировать data.js для этого не нужно.
//
// Поле "photo" — РУЧНОЕ переопределение (путь к файлу или прямая
// ссылка на изображение) для персонажей без id. Приоритетнее id.
//
// Допустимые значения для полей ниже — СТРОГО из списков (если
// неизвестно — оставляйте "-"):
//   family (Семья):     Аллен, Крэндалл, Вурхиз
//   activity (Активность): Сверхидеальная, Идеальная, Хранитель Игровой,
//     Частичка Игровой, Император Игровой, Ходячий миф, Легенда сайта,
//     Любимый кот, Замечательнейшая, Замечательная, Улучшающаяся,
//     Положительная, Переходная, Отрицательная, Ухудшающаяся, Ужасная,
//     Ужаснейшая, Забытый кот, Забывший про игру, Покинувший игру,
//     Подлежащий удалению, Пустое место
//   power (БУ):          Блоха, Котёночек, Задира, Гроза детской,
//     Страх барсуков, Победитель псов, Защитник племени, Великий воин,
//     Достоин Львиного племени, Идеальная
//   position (Должность): Старший семьи Крэндалл, Старший семьи Аллен,
//     Старший семьи Вурхиз, Питомец семьи Крэндалл, Питомец семьи Аллен,
//     Питомец семьи Вурхиз, Котенок
//   gender (Пол):        Кот, Кошка
//   status (Статус):     перерод, не перерод
// ============================================================

const characters = [
  {
    id: "",
    name: "Порочный Принц",
    age: 41,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Идеальная",
    family: "Крэндалл",
    position: "Старший семьи Крэндалл",
    gender: "Кот",
    photo: "images/порочный-принц.png"
  },
  {
    id: "",
    name: "Отрада Королевства",
    age: 47,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1552161",
    name: "Принц Бездны",
    age: 267,
    status: "не перерод",
    activity: "Хранитель Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "205834",
    name: "Ушастик",
    age: 12.5,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1687438",
    name: "Ирисочка",
    age: 62.9,
    status: "не перерод",
    activity: "Сверхидеальная",
    power: "Великий воин",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1605257",
    name: "Стелла",
    age: 201,
    status: "не перерод",
    activity: "Ухудшающаяся",
    power: "Защитник племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1396482",
    name: "Торо",
    age: 42.2,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Победитель псов",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1685836",
    name: "Мягко-Хвостик Скитлс",
    age: 51,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1642613",
    name: "Цапик",
    age: 137.5,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Хэй-Хэй Хэй",
    age: 28.6,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1428176",
    name: "Ханна-Любовный Треугольник",
    age: 120.2,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1703828",
    name: "Не-Буди Лихо",
    age: 13.5,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Страх барсуков",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1613660",
    name: "Заяц",
    age: 53.2,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1108170",
    name: "Маленькая Плутовка",
    age: 133.2,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1644888",
    name: "Растяпа",
    age: 133.2,
    status: "не перерод",
    activity: "Подлежащий удалению",
    power: "Страх барсуков",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1684853",
    name: "Сахарок",
    age: 53.2,
    status: "не перерод",
    activity: "Забывший про игру",
    power: "Задира",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1184085",
    name: "Крок-Мадам",
    age: 153,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Победитель псов",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1613659",
    name: "Дэдпул-Шептунчик",
    age: 189.9,
    status: "не перерод",
    activity: "Подлежащий удалению",
    power: "Гроза детской",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1707179",
    name: "Миннесотский Сорокопут",
    age: 7.6,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Блоха",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1685736",
    name: "Сорока-Воровка",
    age: 51.2,
    status: "не перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1245956",
    name: "Старушка-Мика Лин",
    age: 120.4,
    status: "перерод",
    activity: "Ходячий миф",
    power: "Защитник племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1701697",
    name: "Элио",
    age: 18,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1655135",
    name: "Кэт-Китти Кэт",
    age: 16.4,
    status: "перерод",
    activity: "Ухудшающаяся",
    power: "Гроза детской",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1372562",
    name: "Парящая Гарпия",
    age: 44.3,
    status: "перерод",
    activity: "Император Игровой",
    power: "Гроза детской",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1291300",
    name: "Маленький-Плут",
    age: 132.9,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1468562",
    name: "Оно",
    age: 26,
    status: "перерод",
    activity: "Ходячий миф",
    power: "Страх барсуков",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1023684",
    name: "Король-Ада Кроули",
    age: 26.4,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1698173",
    name: "Падший-Ангел Кастиэль",
    age: 25.4,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1602814",
    name: "Лысик",
    age: 204.4,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1706756",
    name: "Похоть",
    age: 8.5,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1692261",
    name: "Скромница-Твайла",
    age: 38.1,
    status: "не перерод",
    activity: "Ходячий миф",
    power: "Гроза детской",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1689390",
    name: "Эвти",
    age: 44,
    status: "не перерод",
    activity: "Ужасная",
    power: "Задира",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1651435",
    name: "Мисс-Ведьмочка",
    age: 46.8,
    status: "перерод",
    activity: "Ужасная",
    power: "Задира",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1707142",
    name: "Креветка-Шримпрол",
    age: 7.7,
    status: "не перерод",
    activity: "Любимый кот",
    power: "Победитель псов",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Шмыгля-Мокрый Нос",
    age: 120,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Страх барсуков",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "1348287",
    name: "Вентилятор",
    age: 157,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Достоин Львиного племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "1390311",
    name: "Противостояние",
    age: 25.7,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Йоль",
    age: 50.6,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "Крэндалл",
    position: "Питомец семьи Крэндалл",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Дурашка-Рыжая Лисичка",
    age: 42,
    status: "не перерод",
    activity: "Ходячий миф",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Джон-Доу",
    age: 31.5,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Хэй-Итсми Ветири",
    age: 4.5,
    status: "не перерод",
    activity: "Легенда сайта",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Бард-Мурзильник Холодильник",
    age: 14.3,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Тайны",
    age: 16.2,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Крошка-Максин",
    age: 7.5,
    status: "-",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Сайко",
    age: 121.6,
    status: "-",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Дерлорд",
    age: 28.5,
    status: "-",
    activity: "Ходячий миф",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Кытя",
    age: 4.7,
    status: "перерод",
    activity: "Любимый кот",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Шпинат",
    age: 136,
    status: "-",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Райан",
    age: 8,
    status: "-",
    activity: "Замечательнейшая",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Гримуар",
    age: 210,
    status: "перерод",
    activity: "Улучшающаяся",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Мелейс-Лиловая Нежность",
    age: 120,
    status: "перерод",
    activity: "Император Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Альфред-Ф Джонс",
    age: 64,
    status: "перерод",
    activity: "Забывший про игру",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Заснеженный-Куст Ежевики",
    age: 79,
    status: "-",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Амамия Рэн",
    age: 19.7,
    status: "-",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Гад-Морской",
    age: 141,
    status: "перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Чернопоп",
    age: 37,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Богом-Забытая Тундра",
    age: 63,
    status: "-",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Геннадайос",
    age: 194,
    status: "-",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Джордж-Рассел",
    age: 25,
    status: "-",
    activity: "Ходячий миф",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Перламутр",
    age: 61,
    status: "-",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Полосатогрудик",
    age: 6.8,
    status: "перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Фолли",
    age: 167,
    status: "-",
    activity: "Император Игровой",
    power: "Идеальная",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Гро-Горот",
    age: 73,
    status: "перерод",
    activity: "Император Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Юкки-Искательница Приключений",
    age: 28,
    status: "-",
    activity: "Ходячий миф",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Ясный-Полумесяц",
    age: 209,
    status: "-",
    activity: "Хранитель Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "фейд",
    age: 206,
    status: "-",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Немой",
    age: 75,
    status: "перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Авис-Повелительница Птиц",
    age: 209,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Доши-Деринг",
    age: 91,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Скарфея",
    age: 129,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Проказница-Трясопопка",
    age: 7.9,
    status: "-",
    activity: "Ходячий миф",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Стефан-Польски",
    age: 19.2,
    status: "-",
    activity: "Положительная",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Джулиан",
    age: 41.3,
    status: "-",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Томас",
    age: 16,
    status: "перерод",
    activity: "Император Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Кочевряжка",
    age: 8,
    status: "перерод",
    activity: "Император Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Эклипс",
    age: 25,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Раззл-Даззл",
    age: 89,
    status: "перерод",
    activity: "Император Игровой",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Нутелла",
    age: 69,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Скиттлс",
    age: 16,
    status: "перерод",
    activity: "Ходячий миф",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Незаметный",
    age: 259,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Танец Мертвецов",
    age: 79,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Миллениум-Лунная Радуга",
    age: 187,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Вифлием",
    age: 15,
    status: "перерод",
    activity: "Император Игровой",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Матчалатте",
    age: 5,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Чуня",
    age: 138,
    status: "перерод",
    activity: "Ужасная",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Цветение Сакуры",
    age: 141,
    status: "перерод",
    activity: "Покинувший игру",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Полуночный-Баловень",
    age: 171,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Рёва-Корова",
    age: 67,
    status: "перерод",
    activity: "Забытый кот",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Неля",
    age: 4,
    status: "перерод",
    activity: "Император Игровой",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Ресничка-На Щеке",
    age: 114,
    status: "не перерод",
    activity: "Забывший про игру",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Сариил",
    age: 215,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Призор",
    age: 12,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Венценосец",
    age: 124,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Люмен-Золото Дураков",
    age: 47,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Вжик-Вжак",
    age: 115,
    status: "перерод",
    activity: "Ходячий миф",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Господин-Малыш",
    age: 272,
    status: "перерод",
    activity: "Ужаснейшая",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Плакучая Ива",
    age: 16,
    status: "перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Немка",
    age: 46,
    status: "не перерод",
    activity: "Замечательная",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Караул",
    age: 43,
    status: "не перерод",
    activity: "Замечательная",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Пациент",
    age: 39,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Энакин",
    age: 118,
    status: "перерод",
    activity: "Ужаснейшая",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Санбрингер",
    age: 5,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Лень",
    age: 261,
    status: "не перерод",
    activity: "Ужаснейшая",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Торф",
    age: 41,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Созвездие Вспышки",
    age: 12,
    status: "перерод",
    activity: "Император Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Сов",
    age: 69,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Малышка Крул",
    age: 54,
    status: "перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Рубедо",
    age: 57,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Слизнекот",
    age: 189,
    status: "перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Велиара",
    age: 184,
    status: "перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Леророшка",
    age: 77,
    status: "не перерод",
    activity: "Покинувший игру",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Трэвис",
    age: 256,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Старина",
    age: 69,
    status: "не перерод",
    activity: "Покинувший игру",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Наёмница-Ада Вонг",
    age: 4,
    status: "не перерод",
    activity: "Ходячий миф",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Киана-Херршер Конца",
    age: 273,
    status: "перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "-",
    position: "-",
    gender: "-",
    photo: ""
  },
  {
    id: "",
    name: "Оффенди",
    age: 190,
    status: "не перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Гекс-Нагави",
    age: 170,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "мс хованский",
    age: 4,
    status: "перерод",
    activity: "Любимый кот",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Жалко",
    age: 60,
    status: "перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Савельюшка",
    age: 28,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Крошка-Матильда",
    age: 67,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Погрызушка",
    age: 114,
    status: "не перерод",
    activity: "Любимый кот",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Шедоу-Счастливая Лапка",
    age: 29,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Котёночек",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Вильямм",
    age: 193,
    status: "перерод",
    activity: "Ужасная",
    power: "Защитник племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Габи-Отчаянная Домохозяйка",
    age: 49,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Анекдот",
    age: 127,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Врунья",
    age: 69,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Дроссель",
    age: 76,
    status: "перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Мамочка-Мышка",
    age: 45,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Молчанье",
    age: 138,
    status: "перерод",
    activity: "Частичка Игровой",
    power: "Достоин Львиного племени",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Иерихон-Творение Зеквиеля",
    age: 180,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Страх барсуков",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Скрепка",
    age: 189,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Хатчерсон",
    age: 54,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Гроза детской",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Духовея",
    age: 10,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Милашка-Отзеркаленная Водица",
    age: 38,
    status: "не перерод",
    activity: "Частичка Игровой",
    power: "Великий воин",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Эрико Фукадава",
    age: 25,
    status: "не перерод",
    activity: "Император Игровой",
    power: "Задира",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Яркое-Полуденное Солнце",
    age: 158,
    status: "не перерод",
    activity: "Хранитель Игровой",
    power: "Идеальная",
    family: "-",
    position: "-",
    gender: "Кот",
    photo: ""
  },
  {
    id: "",
    name: "Серпантин",
    age: 260,
    status: "перерод",
    activity: "Ужасная",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  },
  {
    id: "",
    name: "Сакура-Ча Непобедимая",
    age: 26,
    status: "перерод",
    activity: "Император Игровой",
    power: "Победитель псов",
    family: "-",
    position: "-",
    gender: "Кошка",
    photo: ""
  }
];
